### PR TITLE
Library set options

### PR DESCRIPTION
**Pull request by MaitreDede**
Add a way to update (some) matrix options at runtime.

### CODE REVIEW

**Comment by MaitreDede** [comment]
Issue https://github.com/hzeller/rpi-rgb-led-matrix/issues/424.
Not yet tested.

**Comment by MaitreDede** [comment]
Brightness tested ok (brightness set to 0 will make it 100%).

**Comment by hzeller** [comment]
So this might be confusing to the user as only few options can even be changed after a matrix has been updated. Even with more documentation this might be confusing.
So I might be more in favor of specific setters for certain fields (such as brightness)

**Comment by MaitreDede** [comment]
Ok, I will do accordingly with latest version.

**Pull request closed without merging**
