### PR TITLE
Add API documentation to Python bindings

### PR DESCRIPTION
**Pull request by BenjaminPelletier**
This is primarily in response to #1170.  Also, this PR fixes a few minor grammar issues in the documentation.

### CODE REVIEW

**Comment by hzeller** [comment]
Thanks.

**Comment by daveythacher** [comment]
Just to be clear this security measure is only as good as the application that calls this library. If there is a noticeable delay in the call to init the library/matrix, bad stuff can still happen. At that point full privilege's will exist. This code base would likely fail or be blocked on critical systems following a security review.

I suspect the reason for why it does this has to do with performance. One could isolate the library into its own process, but communication between processes may prove degrading. A front end library would also likely exist for application code. This would prevent application code from running in super user state, unless required. Basically creating a user space driver or following a microkernel approach.

Now one could manually extent this functionality using the existing functionality.

**Comment by hzeller** [comment]
This is why people are given the choice of doing the privilege dropping themselves. But the default tries to be as useful as possible for the user who doesn't know how to do that.

**Comment by daveythacher** [comment]
I think this should be backed out. It is not technically correct. Even if running as daemon and file is owned by Pi, the file could still be accessed if global access permission are set correctly. This file is not likely critical enough to be blocked from other users. If it is critical the code could be changed to make it jump to Pi instead of daemon.

However recommending running an application as super user all the time is probably critical.

**Comment by daveythacher** [comment]
Technically Linux would expect you do hardware operations in the kernel then communicate via a sysfs like interface. That could be slow, however it provides division of privilege's in the manner at the core of Linux security. This could isolate the need for root out of user space and more importantly the library.

Overall if you use a better notion of hardware you can avoid these problems. For example you can grant access to things like SPIDEV, which will allow any process running under those users to have full control over devices connected to bus. However the kernel could still restrict this some.

For this project there is still issues. This process just maps into /dev/mem for IO and PWM control. A kernel driver could replace this. You can make an interface which work at filesystem however complexity can rise there. Overall the kernel is supposed to manage hardware. However these notions create overhead which are problematic for this approach.

This project shows a poor understand standing of user space vs kernel space. It also shows a poor understanding of embedded devices. Proceeding with this notion will create issues. Software centric design is not stable. Technically what you are trying to do is possible. In certain cases this project will work. It is the library part that actually really invites issues. 

However not exactly. Overall what causes issues is the context of existence. It is undefined, and therefore can be defended and attacked at will. There is a way to make stuff like this work, however the Pi really makes that a pain. It is conceptually too software centric. Python has become a joke.

**Comment by hzeller** [comment]
Talk is cheap. Show me the code.
If you want to contribute, send pull requests, David.

**Pull request merged**
