### PR TITLE
bindings/python: Add priv_drop_user and priv_drop_group

### PR DESCRIPTION
**Pull request by somechris**
This gives Python users control over which user/group the process is dropped into.

### CODE REVIEW

**Comment by hzeller** [comment]
Sorry for the delay, just going through old PRs :)
Could you re-base as the Python bindings have been touched recently.

**Comment by somechris** [comment]
Will do, but it'll take me a few days to get to it.

**Comment by hzeller** [comment]
The generated files are not included anymore to avoid staleness so only changes in the *.pyx need to be submitted. So I suspect it will be fairly straigthforward to update the patch.

**Comment by somechris** [comment]
> Could you re-base as the Python bindings have been touched recently.

Done.

Thanks for removing the `core.cpp`. It's so much simpler without it! \o/

**Comment by hzeller** [comment]
Thanks, merged!

**Pull request merged**
