### PR TITLE
Zmq server

### PR DESCRIPTION
**Pull request by depili**
This pull request adds a very simple zeromq server to the library examples. This is a refinement of the code presented in issue #181

### CODE REVIEW

**Comment by hzeller** [comment]
mmh, this looks highly specialized to your use-case. Why a complicated zmq socket that requires external dependencies instead of just a simple TCP socket protocol. Your program would be about as short without all the dependency overhead.

**Comment by depili** [comment]
ZMQ deals with breaking up the data into multiple packets if the payload is too large and has bindings for just about every language out there so its pretty universal protocol.

**Comment by depili** [comment]
And one of the reasons why I went with zeromq instead of a simpler udp implementation is that I ran into OSX's udp packet size limit when trying to send 32x128 pixels worth of rgb data.

**Comment by akatrevorjay** [comment]
This is great, thank you!

**Comment by aycgit** [comment]
@depili the idea is great but before this can be merged i suggest you atleast add a minimal api for sending text/images

**Comment by hzeller** [comment]
This is just the library to control the underlying display; any server code to connect to it over the network should be done separately anyway (I suggest by using this library here as a sub-module).

This library does intentionally not suggest any particular way how to interact with the display over the network (in particular not with something requiring an external library like zmq), as this would be the realm of application code. So, this pull request can not be accepted here, but I leave it here for people to draw inspirations.

There are already various examples of other server protocols; for instance
  * [FlaschenTaschen](https://github.com/hzeller/flaschen-taschen/tree/master/server#rgb-matrix-panel-display) provides a layer-composite display over the networks using UDP. Also comes with utitilities to send text or images. The VLC player natively supports FlaschenTaschen to show videos.
  * [PixelPusher](https://github.com/hzeller/rpi-matrix-pixelpusher) implements the PixelPusher protocol, common in certain lighting applications. Supported by Processing and LedLabs.
  * Or here is an old gist I made as an example with a simple [UDP server](https://gist.github.com/hzeller/9ece7d7150c6d28ed1825eee85b5d243)  (if at all, something like this might be considered to be included as an example, as it does not need any additional dependencies).

**Comment by Knifa** [comment]
Hope it's OK to add this as a comment (since this is being left open for people to find look) --- if folk are really looking for a ZMQ-based frame server, I've spun up a project for this here. There's a Docker image available so it's ready to go. I found this to be a much easier paradigm to deal with rather than using the bindings.

https://github.com/Knifa/led-matrix-zmq-server

**Comment by hzeller** [comment]
I've mentioned your implementation in the README now @Knifa so that people can find it there.

**Pull request closed without merging**
