### PR TITLE
Fast Python SetImage implementation

### PR DESCRIPTION
**Pull request by chmullig**
I implemented a fast version of SetImage in pure cython. It works by accessing the underlying PIL image buffer directly, following the discussion here: https://groups.google.com/forum/#!topic/cython-users/Dc1ft5W6KM4. I set it as the default, but the old implementation is available with a simple flag on the SetImage call, because it works by accessing PIL's internal unsafe_ptrs, although it actually seems reasonably safe in this case since we aren't retaining or passing the pointers around to other threads, etc.

The code cython generates in the pixel copying loop doesn't interact with python at all, so it's very fast:
annotated_cython

I ran a small benchmark to test on a current Raspberry Pi 3, scrolling the runtest16.ppm image for 2^15 frames as fast as possible in C++, with the existing Python implementation (--slow), and with this new one (--fast). The fast version is very close to the C++. 

[benchmark.cc](https://github.com/hzeller/rpi-rgb-led-matrix/files/691741/benchmark.cc.txt)
[benchmark.py](https://github.com/hzeller/rpi-rgb-led-matrix/files/691742/benchmark.py.txt)

```
pi@chrismpi3:~/rpi-rgb-led-matrix/examples-api-use $ time sudo ./benchmark -r 16 -c 2 -b 25 runtext16.ppm 
Size: 64x16. Hardware gpio mapping: adafruit-hat-pwm
Read image 'runtext16.ppm' with 281x16
Press <CTRL-C> to exit and reset LEDs

real	1m12.723s
user	0m40.700s
sys	0m3.130s
pi@chrismpi3:~/rpi-rgb-led-matrix $ cd ../python/samples/
pi@chrismpi3:~/rpi-rgb-led-matrix/python/samples $ time sudo python3 benchmark.py -r 16 -c 2 -b 25 -i ../../examples-api-use/runtext16.ppm --slow
Press CTRL-C to stop sample

real	2m10.764s
user	2m5.090s
sys	0m5.040s
pi@chrismpi3:~/rpi-rgb-led-matrix/python/samples $ time sudo python3 benchmark.py -r 16 -c 2 -b 25 -i ../../examples-api-use/runtext16.ppm --fast
Press CTRL-C to stop sample

real	1m13.218s
user	0m40.930s
sys	0m2.350s
pi@chrismpi3:~/rpi-rgb-led-matrix/python/samples $ 
```

### CODE REVIEW

**Comment by hzeller** [comment]
Wow, that is very nice!

I've done a quick test on my test-Pi and it looks indeed much faster.

When I run the image-draw.py example, it complains about SetPixelsPillow for some reason; probably you know exactly what is happening here:

```
Traceback (most recent call last):
  File "./image-draw.py", line 39, in <module>
    matrix.SetImage(image, n, n)
  File "rgbmatrix/core.pyx", line 22, in rgbmatrix.core.Canvas.SetImage (rgbmatrix/core.cpp:1469)
AttributeError: 'rgbmatrix.core.RGBMatrix' object has no attribute 'SetPixelsPillow'
```

Happy to merge when we get this sorted.

**Comment by chmullig** [comment]
Great. I think that's fixed now – SetPixelsPillow was in FrameCanvas when it should have been in Canvas.

**Comment by hzeller** [comment]
Wonderful, thank you! Merged. This was some pain-point using the Python implementation, so this will make some folks happy.

[ Since you seem to be knowledgeable using cython, maybe you might be interested in looking into issue #264 and contributing a pull request ? It is mostly about creating the Matrix using the convenience functions ParseOptionsFromFlags() and CreateMatrixFromOptions() to create the matrix. But I have no idea how to access argc/argv in the Python interpreter. ]

**Comment by chmullig** [comment]
Awesome, thanks so much!

I'll take a look at that, doesn't sound too bad.

**Comment by danielvy** [comment]
I gave a shot addressing issue #264 , there is a summary in my comment there. Mentioning it here so @chmullig doesn't do duplicate work (unless he really wants to :) )

**Comment by partofthething** [comment]
FYI, I'm still seeing this error from `image-draw.py` in the samples folder on the latest `master`. Any ideas?

**Pull request merged**
