### PR TITLE
added image-viewer

### PR DESCRIPTION
**Pull request by aycgit**
really suprised this wasn't in here yet since it was in the readme.

### CODE REVIEW

**Comment by hzeller** [comment]
The image viewer mentioned in the READMEs is in the `utils/` directory.
Having said that, this is a useful Python example.

**Comment by aycgit** [comment]
im testing it right now, is there any way to position the image on the matrix using  python?

**Comment by hzeller** [comment]
There is an `offset_x` and `offset_y` parameter to the `SetImage()` function.

**Comment by aycgit** [comment]
thanks, best lib ever :)

**Pull request merged**
