### PR TITLE
Implement z-arrangement pixel mapper

### PR DESCRIPTION
**Pull request by lehni**
This pixel mapper allows for these kind of arrangements:
```
1 … 2
  /
3 … 4 
  /
5 … 6
```

### CODE REVIEW

**Comment by hzeller** [comment]
This doesn't look like it takes parallal chains into account in which the parallel chains are also arranged that way. Can you update the code to do that ?
(This would be useful for #1003 )

**Comment by marcmerlin** [comment]
@lehni  If you have a parallel output board, can you look at Vmapper that just got submitted and would allow you to run 1-3-5 and 2-4-6 in parallel?
Also, if you have a single chain and turn your panels 3 and 4 upside down to have the shortest cables possible, wouldn't that work with the existing U-mapper?

**Comment by lehni** [comment]
I don't have a parallel board. Maybe somebody else can take it from here? I wrote this mostly for my own needs and thought I could share it, but I don't have the time to work more on it for a feature that I don't need and can't test. I hope you understand.

**Comment by marcmerlin** [comment]
@lehni , Henner just made me realize that my code already does that you needed, so we don't need to merge yours anymore.
Let's assume that your panels are 64x32:
please try mapper=V-mapper --led-rows=32 --led-rows=128 --chain=3 --mapper=V-mapper
This should just work with your panels by pretending that your 2 panels wide are a single panel of 128 wide.

Can you confirm?

**Comment by lehni** [comment]
Sadly I don't have access to the setup right now due to the Corona / WFH rules in Switzerland. I don't know when I'll next be in a situation where I can test this, but I will let you know when I did.

**Comment by hzeller** [comment]
Could you confirm if @marcmerlin 's V-Mapper helps your use-case @lehni ?

**Pull request closed without merging**
