### PR TITLE
 Set brightness for all created FrameCanvas instances at runtime

### PR DESCRIPTION
**Pull request by vapiper**
When you use  double or multibuffering, calling the `RGBMatrix::SetBrightness` method changes the brightness of the active frame, other frames are displayed with the previous brightness value.
I made changes in the method `RGBMatrix::SetBrightness`.  Now the brightness is set for all instances of the `FrameCanvas` class. This can be used to automatically adjust the brightness of the matrix at runtime, e.g. from a light sensor.

### CODE REVIEW

**Comment by hzeller** [comment]
Thanks, I have mostly a stylistic request before we can merge this.

**Comment by vapiper** [comment]
What did you mean "mostly a stylistic request"?
If I got you right, the method code should be like this.:
```
void RGBMatrix::SetBrightness(uint8_t brightness) {
  for (size_t i = 0; i < created_frames_.size(); ++i) {
    created_frames_[i]->framebuffer()->SetBrightness(brightness);
  }
  params_.brightness = brightness;
}
```

**Comment by hzeller** [comment]
Doh, github does not submit the comment I had pending when I sent the reply. Apparently I had to press another button. Sorry about that.

Yes, that was what I meant...

**Comment by vapiper** [comment]
Ok. I changed the code style.

**Comment by hzeller** [comment]
Thanks, merged!

**Pull request merged**
