### PR TITLE
Add GitHub actions CI to ensure PRs compile

### PR DESCRIPTION
**Pull request by TDHolmes**
It compiles on ubuntu so it obviously isn't perfect (there seems to be a few extra warnings), but it can at least be a sanity check on PRs.

### CODE REVIEW

**Comment by TDHolmes** [comment]
An action should have been triggered on this PR - perhaps actions are disabled on this repo?

**Comment by hzeller** [comment]
What would I have to do to enable actions ?

**Comment by TDHolmes** [comment]
I think the issue might be in Settings -> Actions tab -> Actions permissions. Is this set to disabled for this repo?
image

**Comment by TDHolmes** [comment]
Or perhaps it doesn't run because it is a PR from a forked repo? [Here](https://github.com/TDHolmes/rpi-rgb-led-matrix/pull/2) is the same branch as a PR into my fork, so you can see how actions look like (the green check / red X on the commit as well as checking out the "show all checks" button near the bottom)

**Comment by hzeller** [comment]
It is set enabled. Maybe we have to first get the initial yml file in ? Let me merge, then we see.

**Comment by TDHolmes** [comment]
image
success!

**Comment by hzeller** [comment]
Yay!

thanks!

**Pull request merged**
