### PR TITLE
Add section on how to use this driver with arduino code

### PR DESCRIPTION
**Pull request by marcmerlin**

### CODE REVIEW

**Comment by marcmerlin** [comment]
Hi @hzeller , just changed this to include the image in tree as per your suggestion in the other CL.
Does this look better now?

**Comment by hzeller** [comment]
While I understand that you like to promote your work, it is not needed in the already too large README describing *this* library and will just confuse people.

I'd be open though if you add a link to your description in [the section](https://github.com/hzeller/rpi-rgb-led-matrix#utilities) that describes external uses of the library.

**Comment by marcmerlin** [comment]
Ack. I gave it another shot, how about this?
https://github.com/hzeller/rpi-rgb-led-matrix/pull/1018

**Comment by marcmerlin** [comment]
this is a dupe, closing

**Pull request closed without merging**
