### PR TITLE
Allow Hardware PWM with Adafruit HAT

### PR DESCRIPTION
**Pull request by flowztul**
I connected GPIO 4 and 18 on the Adafruit HAT (see the holes at the top, below the pin header http://www.adafruit.com/images/970x728/2345-04.jpg), now hardware PWM seems to work with these changes.

### CODE REVIEW

**Comment by hzeller** [comment]
Nice, thanks!

**Comment by bmoore27** [comment]
Hi, Quick question. When you say you connected 4 and 18, did you connect them to each other or to the RPi some how?

**Comment by hzeller** [comment]
>
> Hi, Quick question. When you say you connected 4 and 18, did you connect
> them to each other or to the RPi some how?
>
On the Adafruit HAT, there are already two solder-pads that are labelled
like that. You just need to connect these.

**Comment by BorisFR** [comment]
Work great, thanks!

**Pull request merged**
