### PR TITLE
secure radius-max

### PR DESCRIPTION
**Pull request by Jeada91**
Hello, just a little proposition to secure radius_max value that hang and reboot my raspberry PI because I have 64 cols*32 rows and radius_max was computed to 32 and this value is outside of my dot matrix display.

### CODE REVIEW

**Comment by hzeller** [comment]
mmh, this should _never_ hang and crash the system as pixel coordinates should be checked if they are out of range.
If so, something else needs to be fixed. I'll have a look.

**Comment by Jeada91** [comment]
effectively it seems my PI hangs for another reason because when circle expansion goes out the matrix panel it crash at different time and not exactly at first drawing outside my panel.
I'll do some other investigations
Thanks for your reply

**Comment by Jeada91** [comment]
My problem isn't due to software failure but hardware failure. After several test I've orbserved that my RPI hangs with a lot of pixel iluminated independtly of pixels going out of the matrix.
As my RPI is on the same power supply (chineese 10A) than my DMD, power supply is not able to respond to the demand of current
By reducing birghtness all works well.

**Comment by hzeller** [comment]
Cool finding. The power spikes are particularly harsh on power supplies; having separate wires from your matrix to the power supply and the pi to the power supply and capacitors directly at the matrix and Pi can help.

**Pull request closed without merging**
