### PR TITLE
Python - Allow the user to specify the text to scroll via a command line flag.

### PR DESCRIPTION
**Pull request by onebeartoe**
I want to use this script and be able to specify the text to scroll.

### CODE REVIEW

**Comment by onebeartoe** [comment]
@hzeller Do you have any feedback on what is missing/needed to accept his pull request?

I'd like to use the original project (yours and not my fork) in the guide I created for a installing and using a Web interface to rpi-rgb-led-matrix.

https://learn.adafruit.com/raspberry-pi-rgb-led-matrix-webapp

**Comment by hzeller** [comment]
Thanks merged!
There was nothing wrong with it, I just didn't see it before :)

**Comment by onebeartoe** [comment]
Thank you, sir!

**Comment by hzeller** [comment]
FYI, there is another pull request #265 that moves the flag to the text python file. You might want to have a look in case that changes your tutorial.

**Comment by onebeartoe** [comment]
Will do. Thanks again.

**Comment by whatismyname185** [comment]
Hi, onebeartoe…..I've tried your project that's posted at adafruits many times and am not getting it to work at all...can you please update.

**Comment by onebeartoe** [comment]
@whatismyname185 Please don't hijack this thread about scrolling text for the hzeller/rpi-rgb-led-mtrix command line application.  Hit up the Adafruit support forums for your issue and if that does not help then reach out to me on the feedback form on my website (see the link in my github profile).

**Pull request merged**
